stages:
  - prepare
  - lint

include:
  # Prepare
  - project: 'intern/runner-templates'
    ref: "3.5"
    file: '/symfony/install-dependencies.yml'

  # Lint
  - project: 'intern/runner-templates'
    ref: "3.5"
    file: '/php/phan.yml'
  - project: 'intern/runner-templates'
    ref: "3.5"
    file: '/php/composer-require-checker.yml'
  - project: 'intern/runner-templates'
    ref: "3.5"
    file: '/php/composer-unused.yml'

install-dependencies:
  before_script:
    - /bin/true
  except:
    - master
    - tags

composer-require-checker:
  except:
    - master
    - tags

composer-unused:
  except:
    - master
    - tags

php-analysis:
  except:
    - master
    - tags
