stages:
  - prepare
  - static

install-dependencies:
  stage: prepare
  image: drenso/php:7.1-d1
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}_cache"
    expire_in: 1 hour
    paths:
      - vendor/
  before_script:
    - ./install-composer.sh
  script:
    - php composer.phar install --no-interaction --no-progress --no-suggest
  after_script:
    - find vendor/ -name .git -type d -exec rm -rf {} \+
  tags:
    - docker

php-analysis:
  stage: static
  image:
    name: kickin/phan:0.12.2
    entrypoint: [ "" ]
  dependencies:
    - install-dependencies
  script:
    - php7 /opt/phan/phan -k tests/phan/config.php
  tags:
    - docker
