stages:
  - prepare
  - lint

include:
  # Prepare
  - project: 'intern/runner-templates'
    ref: "3.11"
    file: '/symfony/install-dependencies.yml'

  # Lint
  - project: 'intern/runner-templates'
    ref: "3.11"
    file: '/php/phan.yml'
  - project: 'intern/runner-templates'
    ref: "3.11"
    file: '/php/composer-require-checker.yml'
  - project: 'intern/runner-templates'
    ref: "3.11"
    file: '/php/composer-unused.yml'

install-dependencies:
  before_script:
    - /bin/true
  except:
    - master
    - tags

composer-require-checker:
  image: drenso/php:8.0-d1
  before_script:
    - curl -JOL https://github.com/maglnet/ComposerRequireChecker/releases/download/3.2.0/composer-require-checker.phar
  except:
    - master
    - tags

composer-unused:
  before_script:
    - curl -JOL https://github.com/composer-unused/composer-unused/releases/download/0.7.7/composer-unused.phar
  except:
    - master
    - tags

php-analysis:
  except:
    - master
    - tags
